# Generated by Django 3.1.1 on 2020-09-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEHE2_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='msg',
            field=models.TextField(null=True),
        ),
    ]
