# Generated by Django 3.1.1 on 2020-09-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEHE2_APP', '0002_auto_20200910_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
