# Generated by Django 3.1.1 on 2020-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEHE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
