# Generated by Django 3.1.1 on 2020-09-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HEHE', '0003_auto_20200913_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
