# Generated by Django 3.1.1 on 2020-09-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HEHE', '0004_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
