# Generated by Django 3.1.1 on 2020-09-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEHE', '0005_auto_20200913_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hod', models.CharField(max_length=100)),
            ],
        ),
    ]
