# Generated by Django 3.1.1 on 2020-09-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HEHE', '0007_auto_20200913_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sem',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1),
        ),
    ]
